 const ContinentesPaises = [
 {
    continente : "Europa",
    paises: [
      "Albania",
      "Alemania",
      "Andorra",
      "Armenia",
      "Austria",
      "Azerbaiyan",
      "Belgica",
      "Bielorrusia",
      "Bosnia y Herzagovina",
      "Bulgaria",
      "Chipre",
      "Croacia",
      "Dinamarca",
      "Eslovaquia",
      "Eslovenia",
      "España",
      "Estonia",
      "Finlandia",
      "Francia",
      "Grecia",
      "Hungria",
      "Irlanda",
      "Islandia",
      "Italia",
      "Kazajistan",
      "Letonia",
      "Liechtenstein",
      "Lituania",
      "Luxemburgo",
      "Macedonia del Norte",
      "Malta",
      "Moldavia",
      "Monaco",
      "Montenegro",
      "Noruega",
      "Paises Bajos",
      "Polonia",
      "Portugal",
      "Reino Unido",
      "Republica Checa",
      "Rumania",
      "Rusia",
      "San Marino",
      "Serbia",
      "Suecia",
      "Suiza",
      "Turquia",
      "Ucrania",
      "Vaticano"
    ]
  },
{
    continente: "Asia",
    paises: [
      "Afganistan",
      "Arabia Saudita",
      "Azerbayan",
      "Bangladesh",
      "Barein",
      "Birmania",
      "Brunei",
      "Butan",
      "Camboya",
      "Catar",
      "China",
      "Chipre",
      "Corea del norte",
      "Corena del Sur",
      "Egipto",
      "Emiratos Arabes Unidos",
      "Filipinas",
      "Georgia",
      "India",
      "Indonesia",
      "Irak",
      "Iran",
      "Israel",
      "Japon",
      "Jordania",
      "Kazajistan",
      "Kirguistan",
      "Kuwait",
      "Laos",
      "Libano",
      "Macao",
      "Maldivas",
      "Malasia",
      "Myanmar",
      "Mongolia",
      "Nepal",
      "Oman",
      "Palestina",
      "Pakistan",
      "Rusia",
      "Singapur",
      "siria",
      "Sri Lanka",
      "Tailandia",
      "Tayikistan",
      "Timor Oriental",
      "Turkmeistan",
      "Turquia",
      "Uzbekistan",
      "Vietnam",
      "Yemen"
    ]
  },
  {  
    continente: "Africa",
    paises: [
      "Angola",
      "Argelia",
      "Benin",
      "Botsuana",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Camerun",
      "Chad",
      "Comoras",
      "Costa de Marfil",
      "Egipto",
      "Eritrea",
      "Etipia",
      "Gabon",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea Bisau",
      "Guinea Ecuatorial",
      "Kenia",
      "Lesoto",
      "Liberia",
      "Libia",
      "Madagascar",
      "Malaui",
      "Mali",
      "Marruecos",
      "Mauricio",
      "Mauritania",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Republica Centroafricana",
      "Republica Democratica del Congo",
      "Republica del Congo",
      "Sahara Occidental",
      "Ruanda",
      "Santo Tome y Principe",
      "Sengal",
      "Seychelles",
      "Sierra Leona",
      "Somalia",
      "Suazilandia",
      "Sudafrica",
      "Sudan",
      "Sudan del Sur",
      "Tanzania",
      "Togo",
      "Tunez",
      "Uganda",
      "Yibuti",
      "Zambia",
      "Zimbabue",
    ],
  },
  {
    continente: "America",
    paises: [
      "Antigua Barbuda",
      "Argentina",
      "Bahamas",
      "Barbados",
      "Belice",
      "Bolibia",
      "Brasil",
      "Canada",
      "Chile",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Dominica",
      "Ecuador",
      "El Salvador",
      "Estados Unidos",
      "Granada",
      "Groenlandia",
      "Guatemala",
      "Guyana",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Mexico",
      "Nicaragua",
      "Panama",
      "Paraguay",
      "Peru",
      "Republica Dominicana",
      "San Cristobal y Nieves",
      "Santa Lucia",
      "Surinam",
      "Trinidad y Tobago",
      "Uruguay",
      "Venezuela"
    ]
  },
  {
    continente: "Oceania",
    paises: [
      "Australia",
      "Fiyi",
      "Kiribati",
      "Islas Marshall",
      "Micronesia",
      "Nauru",
      "Nueva Zelanda",
      "Papua Nueva Guinea",
      "Islas Salomon",
      "Samoa",
      "Tonga",
      "Tuvalu",
      "Vanutu",
    ]
  }
];
